# Linear Algebra 线性代数

## 1.Overview
求解问题如  
$$y_1=ax_1+bx_2$$  
$$y_2=cx_1+dx_2$$

## 2. Vectors
$$x=[x_1,...,x_n]$$
### Vector Operations
$$x+y=\begin{bmatrix}
x_1 \\
x_2 \\
.\\
.\\
.\\
x_n
\end{bmatrix}+
\begin{bmatrix}
y_1 \\
y_2 \\
.\\
.\\
.\\
y_n
\end{bmatrix}
:=
\begin{bmatrix}
x_1+y_1 \\
x_2+y_2 \\
.\\
.\\
.\\
x_n+y_n
\end{bmatrix}
$$

$$\gamma x:=\begin{bmatrix}
\gamma x_1 \\
\gamma x_2 \\
.\\
.\\
.\\
\gamma x_n
\end{bmatrix}
$$
Python中向量可以写为列表或是元组。

In [1]:
import numpy as np
x = np.ones(3) # Vector of three ones 单位向量
y = np.array((2, 4, 6)) # Converts tuple (2, 4, 6) into array 
x + y


array([ 3.,  5.,  7.])

In [2]:
4 * x

array([ 4.,  4.,  4.])

### Inner Product and Norm
内积和模
$$x'y :=\sum_{i=1}^n x_iy_i$$
$$||x||:=\sqrt{x'x}:=(\sum_{i=1}^n x_i^2)^{1/2}$$

In [3]:
np.sum(x * y) # Inner product of x and y, x′y :=∑xiyi

12.0

In [4]:
np.sqrt(np.sum(x**2)) # Norm of x, take one, 

1.7320508075688772

In [5]:
np.linalg.norm(x) # Norm of x, take two,linalg(Linear + Algebra)

1.7320508075688772

### Span
$A:={a_1,...,a_k}$的线性组合是A的Span：
$$y=\beta_1 a_1+...+\beta_k a_k$$

### Linear Independence 
线性不相关
- A中的任何一个向量不能是A中其他向量的线性组合
- 如果$\beta_1 a_1+...+\beta_k a_k=0$，只能推出$\beta_1=...=\beta_k=0$  

### Unique Representations
如果$A:={a_1,...,a_k}$是线性不相关的，并且如果$y=\beta_1 a_1+...+\beta_k a_k$，那么不存在$y=\gamma_1 a_1+...+\gamma_k a_k$  

## 3.Matrices  
$$A=\begin{bmatrix}
a_{11} & a_{12} & ... & a_{1k} \\
a_{21} & a_{22} & ... & a_{2k} \\
. & .  & & . \\
. & .  & & . \\
. & .  & & . \\
a_{n1} & a_{n2} & ... & a_{nk} 
\end{bmatrix}$$

### Matrix Operations
矩阵乘法、矩阵加法

### Matrices in NumPy

In [6]:
import numpy as np
A = ((1, 2), 
     (3, 4))
type(A)

tuple

In [7]:
A = np.array(A)
type(A)

numpy.ndarray

In [8]:
A.shape

(2, 2)

In [9]:
A = np.identity(3)  # 单位阵
B = np.ones((3, 3)) # 全是1的矩阵
2 * A

array([[ 2.,  0.,  0.],
       [ 0.,  2.,  0.],
       [ 0.,  0.,  2.]])

In [10]:
A + B

array([[ 2.,  1.,  1.],
       [ 1.,  2.,  1.],
       [ 1.,  1.,  2.]])

### Matrices as Maps
方程组可以用矩阵来表示：$f(x)=A_{n*k}x$
$$f(\alpha x+\beta y)=\alpha f(x)+\beta f(y)$$

## 4.Solving Systems of Equations 
$y=Ax$的解释唯一的，当A的列向量是线性不相关的,A是满秩的。

$A\neq 0$时，$x=A^{-1}y$

### More Rows than Columns
不一定有解  

### More Columns than Rows
无解或无穷解，不存在唯一解

### Linear Equations with SciPy

In [11]:
import numpy as np 
from scipy.linalg import inv, solve, det
A = ((1, 2), (3, 4))
A = np.array(A)
y = np.ones((2, 1)) # Column vector 
det(A)              # 行列式值 检测A是否可逆  Check that A is nonsingular, and hence invertible

-2.0

In [12]:
A_inv = inv(A) # A的逆 Compute the inverse A_inv
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [13]:
x = np.dot(A_inv, y) # Solution (Ax=y)  dot 矩阵乘法
np.dot(A, x) # Should equal y

array([[ 1.],
       [ 1.]])

In [14]:
solve(A, y) # Produces same solution

array([[-1.],
       [ 1.]])

## 5.Eigenvalues and Eigenvectors
特徵值与特徵向量  
如果
$$A\nu=\lambda\nu$$
那么$\lambda$是$A$的特征值，$A$是$\lambda$的特征向量。上式等同于$(A-\lambda I)\nu=0$,$A-\lambda I$列向量线性相关时，$\nu$有非零解。

In [15]:
import numpy as np 
from scipy.linalg import eig
A = ((1, 2), (2, 1))
A = np.array(A) 
evals, evecs = eig(A)   # eig 会产生两个变量，一个是特征值，一个是特征向量
evals   # 特征值

array([ 3.+0.j, -1.+0.j])

In [16]:
evecs  # 特征向量

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

### Generalized Eigenvalues
考虑一般化特征值问题
$$A\nu=\lambda B \nu$$
可以通过`scipy.linalg.eig(A,B)`来求解，也可以简化为$B^{-1}A\nu=\lambda\nu$

## 6.Further Topics
### Series Expansions
如果$|a|<1$,那么$\sum_{k=1}^\infty a^k=(1-a)^{-1}$
### Matrix Norms
A是方阵，那么
$$||A||:=\max_{||x||=1}||Ax||$$
左边是向量的模，右边是矩阵的模，例如，对于方阵$S$，条件$|| S || <1$意味着$S$是收缩的，因为它将所有向量拉向原点。
### Neumann’s Theorem 诺伊曼定理
如果对于一些$k\in\mathbb{N}$,有 $||A^k||<1$，且$I-A$是可逆的，就有
$$(I-A)^{-1}=\sum_{k=0}^{\infty} A^k$$
### Spectral Radius
Gelfands公式表明：对于任意方阵A，有
$$\rho(A)=\lim_{k\to\infty}||A^k||^{1/k}$$
这里$\rho(A)$是谱半径，定义为$\max_i |\lambda_i|$，其中$ \{\lambda_i\}_i$是$A$的特征值集。如果特征值全部小于1，那么存在$k$使得$||A^k||<1$。
### Positive Definite Matrices
如果对于每个$x\in\mathbb{R}^n$有$x'Ax>0$，那么A是正定矩阵。

如果对于每个$x\in\mathbb{R}^n$有$x'Ax\geq0$，那么A是半正定矩阵或非负定矩阵。
### Differentiating Linear and Quadratic forms
$z$,$x$,$a$是$n\times1$向量，$A$是$n\times n$矩阵，$B$是$m\times n$矩阵，$y$是$m\times 1$向量。有：  
1. $\frac{\partial a'x}{\partial x}=a$ 
2. $\frac{\partial Ax}{\partial x}=A'$ 
3. $\frac{\partial x'Ax}{\partial x}=(A+A')x$ 
4. $\frac{\partial y'Bz}{\partial y}=Bz$ 
5. $\frac{\partial y'Bz}{\partial B}=yz'$ 